import type { NextPage } from 'next'
import Head from 'next/head'
import gsap from 'gsap'
import ScrollTrigger from 'gsap/dist/ScrollTrigger'
import { useEffect } from 'react'

const Home: NextPage = () => {
  gsap.registerPlugin(ScrollTrigger)

  useEffect(() => {
    const components = document.querySelectorAll('#component')
    const container: HTMLElement = document.querySelector('#container')!
    gsap.to(components, {
      xPercent: -100 * (components.length - 1),
      ease: 'none',
      scrollTrigger: {
        trigger: container,
        pin: true,
        scrub: 1,
        snap: 1 / (components.length - 1),
        end: () => '+=' + container.offsetWidth,
      },
    })
  }, [])

  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>GSAP Horizontal Scroll</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main id='container' className='flex w-[500vw] overflow-x-hidden'>
        <div
          id='component'
          className='bg-slate-900 text-white w-[100vw] h-[100vh] overflow-x-hidden'
        >
          <div className='flex items-center justify-center flex-col gap-4 h-screen max-w-2xl mx-auto'>
            <small className='text-slate-500'>Hi there, I'm</small>
            <h1 className='text-4xl font-bold'>Yousef Omar</h1>
            <p className='text-base text-gray-300 text-center'>
              I am a self-taught passionate software engineer focusing on the
              Frontend web, love learning modern technologies and forms of
              digital expression, am highly motivated, and aspiring for an
              opportunity to prove myself.
            </p>
          </div>
        </div>
        <div
          id='component'
          className='bg-red-500 text-white w-[100vw] h-[100vh] overflow-x-hidden'
        >
          <div className='flex items-center justify-center h-screen'>
            <h2 className='text-4xl font-bold'>Two</h2>
          </div>
        </div>
        <div
          id='component'
          className='bg-stone-700 text-white w-[100vw] h-[100vh] overflow-x-hidden'
        >
          <div className='flex items-center justify-center h-screen'>
            <h2 className='text-4xl font-bold'>Three</h2>
          </div>
        </div>
        <div
          id='component'
          className='bg-amber-700 text-white w-[100vw] h-[100vh] overflow-x-hidden'
        >
          <div className='flex items-center justify-center h-screen'>
            <h2 className='text-4xl font-bold'>Four</h2>
          </div>
        </div>
        <div
          id='component'
          className='bg-teal-700 text-white w-[100vw] h-[100vh] overflow-x-hidden'
        >
          <div className='flex items-center justify-center h-screen'>
            <h2 className='text-4xl font-bold'>Five</h2>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
